### ISSUE TITLE
Background system should be redone

### ISSUE THREAD

**Issue by basiccube** [NightHackreal/TheLeaningTowerofPizza#1]
The way the backgrounds are handled right now makes it really annoying to replace them as every single background in every room needs to be updated to be double the size of the background's sprite (right now the background for the secret rooms are an example of this).

**Comment by basiccube** [comment]
My idea is to make an object that contains all of the background functionality and lets you select the background sprite for all of the different types of backgrounds in the inspector. That object contains code that sets the background's size to be double the size of the sprite. All of the ParallaxBackground nodes in each room will be replaced with this one object.

**Comment by NightHackreal** [comment]
Hm, alright. I do suck at coding but I can probably try. Right now I did change the secret backgrounds (to be fair the space pinball one was a placeholder), so there's that. I prepared an object called "obj_background" which will be like your suggestion.

**Comment by basiccube** [comment]
I've been working on my own version of obj_background, there are a few things missing in my version but it'll do for now.
I'll update the object you made with what I have and will close this issue for the time being.
